name: UCSSMonitor Job and Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run_tests:
    name: Run Jest Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        env:
          UCSS_EMAIL: test@example.com
          UCSS_PASSWORD: testpassword
        run: |
          # Use npm test which uses the Jest config from package.json
          npm test
  
  scrape_and_record:
    needs: run_tests
    runs-on: ubuntu-latest
    outputs:
      remainingData: ${{ steps.run_scraper.outputs.remainingData }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run scraper
        id: run_scraper
        env:
          UCSS_EMAIL: ${{ secrets.UCSS_EMAIL }}
          UCSS_PASSWORD: ${{ secrets.UCSS_PASSWORD }}
        run: |
          # Extract the remaining data from the script output
          output=$(node scripts/scraper.js)
          remaining_data=$(echo "$output" | grep "remaining_data:" | sed 's/remaining_data://g')
          
          # Set output in the correct format
          echo "remainingData=${remaining_data}" >> $GITHUB_OUTPUT
          
      - name: Check scraper output
        run: |
          if [ "${{ steps.run_scraper.outputs.remainingData }}" = "" ]; then
            echo "Login might have failed or data not retrieved."
            exit 1
          fi
          
      - name: Update Gist
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GIST_USER: ${{ secrets.GIST_USER }}
          GIST_ID: ${{ secrets.GIST_ID }}
          REMAINING_DATA: ${{ steps.run_scraper.outputs.remainingData }}
        run: node scripts/update_gist.js

  update_graph:
    needs: scrape_and_record
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Generate graph
        env:
          GIST_USER: ${{ secrets.GIST_USER }}
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          UTC_OFFSET: ${{ secrets.UTC_OFFSET }}
        run: npm run generate-graph
        
      - name: Verify build output
        run: |
          if [ ! -f docs/index.html ]; then
            echo "Error: docs/index.html does not exist."
            exit 1
          elif ! grep -q '<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>' docs/index.html; then
            echo "Error: docs/index.html does not contain the expected Chart.js content."
            exit 1
          fi
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true

  commit_and_push:
    needs: update_graph
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Check for changes
        id: check_changes
        run: |
          git status --porcelain
          if [ -n "$(git status --porcelain)" ]; then
            echo "hasChanges=true" >> $GITHUB_OUTPUT
          else
            echo "hasChanges=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push changes
        if: steps.check_changes.outputs.hasChanges == 'true'
        run: |
          git add .
          git commit -m "Auto update data [skip ci]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
